version: '3'
services:
  httpd:
      image: httpd
      network_mode: host
      volumes:
          - ./TestAssets:/usr/local/apache2/htdocs/
      ports:
          - "80:80"

  selenium:
    image: selenium/standalone-chrome:4.2.1-20220531
    network_mode: host
    ports:
      - 4444:4444
      - 7900:7900
    environment:
      - SE_NODE_MAX_SESSIONS=4

  swift_web_driver:
    &SwiftWebDriver
    build: .
    volumes:
      - .:/SwiftWebDriver
    working_dir: /SwiftWebDriver
    network_mode: host
    environment:
      SELENIUM_URL: http://localhost:4444
    tty: true
    depends_on:
        - selenium
        - httpd

  build:
    <<: *SwiftWebDriver
    command: /bin/bash -xcl "swift build"

  test:
    <<: *SwiftWebDriver
    command: /bin/bash -xcl "swift test -Xswiftc -warnings-as-errors $${SANITIZER_ARG-}"

  shell:
    <<: *SwiftWebDriver
    entrypoint: /bin/bash
