name: Docker Image CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "develop"
      - "master"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: KengoTODA/actions-setup-docker-compose@v1
      with:
        version: '2.14.2'

    # Caching Docker layers based on package.resolved
    - name: Cache Docker layers
      uses: actions/cache@v3
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-docker-${{ hashFiles('package.resolved') }}-${{ hashFiles('Dockerfile')}}-${{ hashFiles('docker-compose.yml')}}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build And Run Docker image
      run: |
        docker-compose build --no-cache
        docker-compose up selenium -d
        docker-compose run test
